package ExceptionHomeWork;

public class ThrowsExample {
	/*static void division(int a, int b) throws ArithmeticException {

		int c = a / b;

		if (c < 0)
			throw new ArithmeticException("Divided By Zero");
		else
			System.out.println(c);

	}

	public static void main(String[] args) {
		try {
			division(25, 0);
		} catch (ArithmeticException e) {
			System.out.println(e);
		}
	
	
	}*/
	
	

}
